In [1]:
import numpy as np

a = np.arange(0,21,1)
b = np.arange(10,51,2)
c = np.arange(5,101,5)

print("0 to 20:", a)
print("Even numbers:", b)
print("5 to 100:", c)

0 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
5 to 100: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [2]:
import numpy as np

a = np.linspace(0,5,10)
b = np.linspace(-10,10,15)

print(a)
print("Length:", len(a))

print(b)
print("Length:", len(b))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [3]:
import numpy as np

a = np.random.rand(10)
b = np.random.randn(3,3)
c = np.random.randint(10,51,(4,5))

print("Random Numbers:\n", a)
print("\nStandard Normal Matrix:\n", b)
print("\nRandom Integer Matrix:\n", c)

Random Numbers:
 [0.7300884  0.90581835 0.36361528 0.54011507 0.72363911 0.25064662
 0.90158215 0.41546884 0.93741001 0.2886583 ]

Standard Normal Matrix:
 [[-0.18468915 -0.39913606  0.12808785]
 [-3.16598368 -0.60472355 -1.43359516]
 [ 0.47805252  1.21083734 -1.46125806]]

Random Integer Matrix:
 [[41 40 21 28 17]
 [20 13 11 34 20]
 [21 29 13 40 18]
 [17 36 33 36 34]]


In [4]:
import numpy as np

v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Addition:", v1+v2)
print("Subtraction:", v1-v2)
print("Element-wise Multiplication:", v1*v2)
print("Dot Product:", np.dot(v1,v2))

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56]
Dot Product: 100


In [5]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Addition:\n", A+B)
print("\nMatrix Multiplication:\n", A@B)
print("\nElement-wise Multiplication:\n", A*B)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [6]:
import numpy as np

arr = np.random.randint(1,101,(4,4))

print(arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Minimum:", arr.min())
print("Maximum:", arr.max())

[[44 23 70 32]
 [62 87 18 94]
 [40 66 29 45]
 [51 56 85 28]]
Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum: 18
Maximum: 94


In [7]:
import numpy as np

arr = np.random.randint(1,51,20)
matrix = arr.reshape(4,5)

print(matrix)
print("Sum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())
print("Maximum in each row:", matrix.max(axis=1))

[[16 31 25  2 39]
 [ 1 33 43  7  6]
 [38 45 46 25 18]
 [ 5  4 47 20  1]]
Sum: 452
Mean: 22.6
Standard Deviation: 16.37192719260625
Maximum in each row: [39 43 46 47]


In [ ]:
import numpy as np

try:
    n = int(input("Enter number of random values: "))

    arr = np.random.randint(10,101,n)

    print("\nArray:")
    print(arr)

    print("Mean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))

    if n % 2 == 0:
        matrix = arr.reshape(2, n//2)
        print("\n2D Array:")
        print(matrix)
        print("Row-wise Sum:", matrix.sum(axis=1))
    else:
        print("\nCannot reshape into a 2D array because the number of elements is odd.")

except ValueError:
    print("Please enter a valid integer.")