In [1]:
import numpy as np

a = np.zeros(8)
b = np.ones((4,4))
c = np.zeros((3,3))

print("1D Array of Zeros:\n", a)
print("\n4x4 Array of Ones:\n", b)
print("\n3x3 Matrix of Zeros:\n", c)

1D Array of Zeros:
 [0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
